### ISSUE TITLE
Feed cache

### ISSUE THREAD

**Issue by verbiricha** [v0l/snort#165]
Cache main feeds so we don't re-request every time we change timelines.

**Comment by v0l** [comment]
This is also vital to restoring scroll position, i think there is an easy way to do this, we can simply cache a list of notes based on the sub id, since these are specific to each page we will be able to simply store the ids of all the events then have a general indexdDb for events which we can lookup

**Comment by verbiricha** [comment]
Huge win for perfomance and UX, let's do it asap
